Develop
Mirror-Image/Andersen_Task_1 pull request #1
Opened 2020-03-09 06:16 UTC by Mirror-Image

2020-03-09 06:53 UTC, EugeneSolovyev requested changes

2020-03-09 06:53 UTC, EugeneSolovyev commented on src/js/ladder/ladder-component.js
> +    table.appendChild(thead);
думаю что тут можно написать какую-то такую абстракцию, которая позволит укоротить код, при этом не скажется на перформансе
Например:
```javascript
export default class Component {
  createElement(tag, inner) {
    let elem = document.createElement(tag);
    elem.innerText = inner;
    return elem;
  }
}
// .........
export default class LadderComponent extends Component {
  /....
  render() {
    //...
    const thNickName = this.createElement('th', 'Nickname');
    const thScore = this.createElement('th', 'Score');
    // ......
  }
}

```

2020-03-09 06:53 UTC, EugeneSolovyev commented on src/js/ladder/ladder-component.js
> +    const sortedModel = this.model.sort((itemA, itemB) => itemB.score - itemA.score);
Зачем тебе нужна сортировка? Может получится сразу создать отсортированный массив?
Также, `Array.prototype.sort()` мутирует оригинальный массив, т.е. у тебя получается после выполнения сортировки `sortedModel === this.model // true`, имей это ввиду

2020-03-09 06:53 UTC, EugeneSolovyev commented on src/js/ladder/ladder-component.js
> +    returnButton.addEventListener('click', this.handleReturn.bind(this));
а как же твоя реализация паттерна Наблюдатель? может как-то можно через неё сделать?

2020-03-09 06:53 UTC, EugeneSolovyev commented on src/js/ladder/ladder-component.js
> +    new CreateGameController(model, view);
думаю что можно было сделать через статические методы и филды, чтобы избавиться от создания нового инстанса, с учётом того что, ты никуда не присваиваешь результат работы конструктора

2020-03-09 06:53 UTC, EugeneSolovyev commented on src/js/play-game/play-game-model.js
> +      || this.checkWin(this.checkedCellsO, data))) {
подобные условия для читаемости лучше выносить в переменные
```javascript
const isPossibleToFindWinner = (this.checkedCellsX.length > 2 || this.checkedCellsO.length > 2) && (this.checkWin(this.checkedCellsX, data) || this.checkWin(this.checkedCellsO, data));
if (isPossibleToFindWinner) {
  // ....
}
```

2020-03-09 06:53 UTC, EugeneSolovyev commented on src/js/play-game/play-game-model.js
> +    });
очень плохо что ты мутируешь тут игрока и модель
это можно оптимизировать через reduce и/или map
для this.currentPlayers будет примерно такое
```javascript
this. currentPlayers = this.currentPlayers.reduce((result, currentItem) => {
  if (currentItem.nick === nickName) {
    currentItem. currentScore += 1;
  }
  return [...result, currentItem];
}, [])
```

2020-03-09 06:53 UTC, EugeneSolovyev commented on src/js/play-game/play-game-view.js
> +      event.target.classList.add('y-color');
вот такие вещи можно обработать через мапу, типа
```javascript
const CLASS_LIST_MAP = {
  'x': 'x-color',
  'o': 'y-color'
}

event.target.classList.add(CLASS_LIST_MAP[this.playerSymbol]);
```
тем самым ты избавляешься от if/else и код выглядит чище (как по мне)
в данном кейсе можно оставить и так как у тебя написано, но вообще пример выше он очень удобен если у тебя очень большая вереница if/elseif/else или длинный switch/case

2020-03-09 06:53 UTC, EugeneSolovyev commented on src/js/play-game/play-game-view.js
> +    scorePayer2.innerText = this.model[1].currentScore;
тут явно можно упросить
```javascript
const [firstPlayer, secondPlayer] = this.model;
const elements = [
  {
    nickID: 'first_player_nick',
    scoreID: 'first_player_score',
    nick: firstPlayer.nick,
    score: firstPlayer. currentScore,
  },
  {
    nickID: 'second_player_nick',
    scoreID: 'second_player_score',
    nick: secondPlayer.nick,
    score: secondPlayer. currentScore,
  }
];
elements.forEach((currentItem) => {
  currentItem.nickID.innerText = currentItem.nick;
  currentItem.scoreID.innerText = currentItem.score;
})

```

2020-03-09 06:55 UTC, EugeneSolovyev commented on src/js/play-game/play-game-view.js
> +    scorePayer2.innerText = this.model[1].currentScore;
тут примерный код

2020-03-16 06:53 UTC, EugeneSolovyev requested changes

2020-03-16 06:53 UTC, EugeneSolovyev commented on src/js/create_game/create-game-view.js
> +    }
предлагаю избавиться от ветвления
```javascript
const MESSAGE_AREA_MAP = {
  x: 'Your symbol is "O"',
  o: 'Your symbol is "X"'
}
//...
toggleSecondPlayerSymbolMessage(symbol) {
  this.seconsPlayerSymbolMessageArea.innerText = MESSAGE_AREA_MAP[symbol]
}
```

2020-03-16 06:53 UTC, EugeneSolovyev commented on src/js/create_game/create-game-view.js
> +          this.runPlay();
это очень сложно выглядит
предлагаю порефачить, если совсем будешь без идей - пингуй

2020-03-16 06:53 UTC, EugeneSolovyev commented on src/js/ladder/ladder-component.js
> +    };
этот объект думаю можно вынести в файл с константами, чтобы не захламлять конструктор, а здесь только импортить его и сеттить в this.data
что скажешь?

2020-03-16 06:53 UTC, EugeneSolovyev commented on src/js/play-game/play-game-model.js
> +    }
смущает такая вложенность, может получится как-то упростить?

2020-03-16 06:53 UTC, EugeneSolovyev commented on src/js/play-game/play-game-model.js
> +    });
когда мы используем цикл в цикле, сложность составляет O(n^2) - это плохо
предлагаю сделать массив this.winCombinations плоским и работать с ним
https://ramdajs.com/docs/#flatten

2020-03-16 06:53 UTC, EugeneSolovyev commented on src/js/play-game/play-game-model.js
> +    }, []);
у тебя разница здесь только в том что в первом случае currentScore, а в другом score
может получится как-то привести к чему-то одному и избавиться от дублей?

2020-03-16 06:53 UTC, EugeneSolovyev commented on src/js/ladder/ladder-component.js
> +    observer.unsubscribe('returnToMainPage', this.handleReturn.bind(this));
предлагаю биндить this в конструкторе
как в реакте прям
```javascript
this.handleReturn = this.handleReturn.bind(this);
```
тут и в целом везде по проекту где это необходимо

2020-03-16 08:38 UTC, Mirror-Image commented on src/js/create_game/create-game-view.js
> +    }
Сделал еще лучше)
![image](https://user-images.githubusercontent.com/51057254/76737874-39b02800-6772-11ea-98df-d99db2eb280d.png)

2020-03-17 06:48 UTC, EugeneSolovyev approved these changes

2020-03-17 06:48 UTC, merged